version: "3"

networks:
  web:
    external: true
  internal:
    external: false

services:
  traefik:
    image: traefik:1.7.2-alpine
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.frontend.rule=Host:monitor.localhost"
      - "traefik.port=8080"
    networks:
      - web

  blog:
    image: wordpress:4.9.8-apache
    environment:
      WORDPRESS_DB_PASSWORD: "password"
    volumes:
      - ./wordpress_data:/var/www/html
    labels:
      - "traefik.backend=blog"
      - "traefik.frontend.rule=Host:blog.localhost"
      - "traefik.docker.network=web"
      - "traefik.port=80"
    networks:
      - internal
      - web
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    networks:
      - internal
    labels:
      - "traefik.enable=false"

  adminer:
    image: adminer:4.6.3-standalone
    labels:
      - "traefik.backend=adminer"
      - "traefik.frontend.rule=Host:db-admin.localhost"
      - "traefik.docker.network=web"
      - "traefik.port=8080"
    networks:
      - internal
      - web
    depends_on:
      - mysql